spring.application.name=spring-ticketing

spring.datasource.url=jdbc:postgresql://localhost:5432/ticketing
spring.datasource.username=postgres
spring.datasource.password=sql
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true

# Pour désactiver la sécurité (à éviter en prod, bien sûr)
spring.security.user.name=admin
spring.security.user.password=admin
